### ISSUE TITLE
rebuild serial port on linux 

### ISSUE THREAD

**Issue by mishkeTz** [nwjs/nw-gyp#114] opened 2017-12-08 15:02 UTC
I am trying to rebuild serialport for linux 64.

I ran this command:

`sudo nw-gyp rebuild --runtime=node-webkit --target=0.25.4 --target_arch=x64`

`gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.2
gyp info using node@9.2.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mishke/Desktop/merrex64/node_modules/serialport/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mishke/.nw-gyp/0.25.4/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/mishke/.nw-gyp/0.25.4',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/nw-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/mishke/.nw-gyp/0.25.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dnw_lib_file=/home/mishke/.nw-gyp/0.25.4/<(target_arch)/nw.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/mishke/Desktop/merrex64/node_modules/serialport',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
/bin/sh: 1: ./content/nw/tools/sysroot_ld_path.sh: not found
gyp: Call to './content/nw/tools/sysroot_ld_path.sh /home/mishke/Desktop/merrex64/node_modules/serialport/build/linux/debian_jessie_amd64-sysroot' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/nw-gyp/lib/configure.js:359:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.10.0-40-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/nw-gyp" "rebuild" "--runtime=node-webkit" "--target=0.25.4" "--target_arch=x64"
gyp ERR! cwd /home/mishke/Desktop/merrex64/node_modules/serialport
gyp ERR! node -v v9.2.0
gyp ERR! nw-gyp -v v3.6.2
gyp ERR! not ok 
`

What am I doing wrong here?

**Comment by rogerwang** [comment] 2017-12-12 01:57
This should be a duplicate of https://github.com/nwjs/nw.js/issues/5971 which was fixed.

**Comment by rogerwang** [comment] 2017-12-12 01:58
Please ask for reopening if it's not.

**Closed as completed by rogerwang** 2017-12-12 01:58 UTC
